apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  namespace: istio-system
  name: peer-authentication
  metadata:
    labels:
      env: {{ .Values.general.env }}
spec:
  mtls:
    mode: DISABLE
