{{/* karpenterはMinikubeで使用できないため、デプロイしない */}}
{{- if ne .Values.global.env "dev" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: karpenter-application
  labels:
    env: {{ .Values.global.env }}
spec:
  project: infra
  destination:
    server: https://kubernetes.default.svc
    namespace: karpenter
  source:
    repoURL: https://charts.karpenter.sh/
    chart: karpenter
    targetRevision: 0.16.3
    helm:
      releaseName: karpenter
      values: |
        serviceAccount:
          annotations:
            eks.amazonaws.com/role-arn: ""
        settings:
          aws:
            clusterName: "foo-eks-cluster"
            clusterEndpoint: "https://*****"
{{- end }}
