apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: prometheus-application
  labels:
    env: {{ .Values.global.env }}
spec:
  project: infra
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 55.5.1
    helm:
      releaseName: kube-prometheus-stack
      values: |
        alertmanager:
          ingress:
            enabled: true
            ingressClassName: nginx
            hosts:
              - {{ .Values.alertmanager.domain }}
          alertmanagerSpec:
            affinity:
              nodeAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  nodeSelectorTerms:
                    - matchExpressions:
                        - key: node.kubernetes.io/nodegroup
                          operator: In
                          values:
                            - system
        grafana:
          ingress:
            enabled: true
            ingressClassName: nginx
            hosts:
              - {{ .Values.grafana.domain }}
        prometheus:
          ingress:
            enabled: true
            ingressClassName: nginx
            hosts:
              - {{ .Values.prometheus.domain }}
          prometheusSpec:
            affinity:
              nodeAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  nodeSelectorTerms:
                    - matchExpressions:
                        - key: node.kubernetes.io/nodegroup
                          operator: In
                          values:
                            - system

  destination:
    server: https://kubernetes.default.svc
    namespace: prometheus
