apiVersion: v1
kind: Service
metadata:
  namespace: microservices
  name: customer-app-service
  labels:
    app: customer
    component: app
    env: {{ .Values.general.env }}
spec:
  type: ClusterIP
  selector:
    app: customer
    component: app
  ports:
    - name: http-customer
      appProtocol: http
      port: 80
      targetPort: 8000
