{{- define "dev.customer.app.deployment" }}
      hostname: {{ .Values.global.serviceName }}-app
      containers:
        # FastAPIコンテナ
        - name: fastapi
          image: {{ .Values.global.serviceName }}-fastapi:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: {{ .Values.global.serviceName }}-app-persistent-volume
              mountPath: /var/www/customer
      volumes:
        - name: {{ .Values.global.serviceName }}-app-persistent-volume
          persistentVolumeClaim:
            claimName: {{ .Values.global.serviceName }}-app-host-path-persistent-volume-claim
{{- end }}
