apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  namespace: services
  name: customer-app-destination-rule
  labels:
    env: {{ .Values.global.env }}
spec:
  exportTo:
    - "*"
  host: customer-app-service.services.svc.cluster.local
