{{- define "prd.orchestrator.app.deployment" }}
      hostname: orchestrator-pod
      containers:
        # FastAPIコンテナ
        - name: fastapi
          image: {{ .Values.aws.accountId }}.dkr.ecr.{{ .Values.aws.region }}.amazonaws.com/orchestrator-fastapi-repository:{{ .Values.image.orchestrator.fastapi }}
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
{{- end }}
