apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  namespace: services
  name: order-app-destination-rule
  labels:
    env: {{ .Values.global.env }}
spec:
  exportTo:
    - "."
  host: order-app-service
