apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  namespace: services
  name: order-virtual-service
  labels:
      env: {{ .Values.global.env }}
spec:
  exportTo:
    - "."
  hosts:
    - "*"
  gateways:
    - mesh
  http:
    - name: order-route
      match:
        - uri:
            prefix: /orders/
      route:
        - destination:
            host: order-app-service.services.svc.cluster.local
            port:
              number: 80
