apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: argocd-application
  labels:
      env: {{ .Values.general.env }}
spec:
  project: default
  source:
    repoURL: oci://{{ .Values.aws.accountId }}.dkr.ecr.{{ .Values.aws.region }}.amazonaws.com/microservices-manifests-kubernetes
    targetRevision: 1.0.0
  destination:
    server: https://kubernetes.default.svc
    namespace: microservices
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
