apiVersion: v1
kind: Secret
metadata:
  namespace: argocd
  name: argocd-kubernetes-secret
  labels:
    env: {{ .Values.general.env }}
    argocd.argoproj.io/secret-type: repository
stringData:
  name: microservices-manifests-kubernetes
  url: {{ .Values.general.aws.accountId }}.dkr.ecr.{{ .Values.general.aws.region }}.amazonaws.com/microservices-manifests-kubernetes
  enableOCI: true
  type: helm
  username: AWS
  password: {{ .Values.general.aws.accountId }}.dkr.ecr.{{ .Values.general.aws.region }}.amazonaws.com
