apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  namespace: argocd
  name: aws-user-argocd-secret
  labels:
    env: {{ .Values.general.env }}
provider: aws
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.aws.user.accessKeyId }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.aws.user.secretAccessKey }}
---
apiVersion: v1
kind: Secret
metadata:
  namespace: argocd
  name: chart-registry-secret
  labels:
    env: {{ .Values.general.env }}
    argocd.argoproj.io/secret-type: repository
stringData:
  name: chart-registry
  url: {{ .Values.aws.user.accessKeyId }}.dkr.ecr.{{ .Values.aws.region }}.amazonaws.com
  enableOCI: "true"
  type: helm
  username: AWS
  password: null
