apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  namespace: argocd
  name: aws-user-argocd-secret
  labels:
    env: {{ .Values.general.env }}
provider: aws
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.aws.user.accessKeyId }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.aws.user.secretAccessKey }}
