apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  namespace: services
  name: {{ .Values.global.serviceName }}-app-gateway
  labels:
    env: {{ .Values.global.env }}
spec:
  selector:
    istio: egressgateway
  servers:
    - port:
        name: http-{{ .Values.global.serviceName }}
        protocol: HTTP
        number: {{ .Values.egressGateway.pod.listenPort }}
      hosts:
        - httpbin.org
