kind: ConfigMap
apiVersion: v1
metadata:
  name: eks-fluent-bit-config-map
  namespace: aws-observability
  labels:
    env: {{ .Values.general.env }}
data:
  output.conf: |
    [OUTPUT]
        Name cloudwatch_logs
        Match *
        region ap-northeast-1
        log_group_name fluent-bit-cloudwatch
        log_stream_prefix from-fluent-bit-
        auto_create_group true
