apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: microservices
  name: order-app-pod
  labels:
    app: order
    component: app
    env: {{ .Values.general.env }}
spec:
  replicas: 1
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0%
  selector:
    matchLabels:
      app: order
      component: app
      env: {{ .Values.general.env }}
  template:
    metadata:
      labels:
        app: order
        component: app
        env: {{ .Values.general.env }}
    spec:
{{- if eq .Values.general.env "dev" }}
  {{- include "dev.order.app.deployment" . }}
{{- end }}
{{- if eq .Values.general.env "prd" }}
  {{- include "prd.order.app.deployment" . }}
{{- end }}