inputs:
  target:
    description: The target of resource
    required: true
  aws_account_id:
    description: AWS account id
    required: true
  aws_account_key_id:
    description: AWS account key id
    required: true
  aws_secret_access_key:
    description: AWS secret access key
    required: true
  aws_default_region:
    description: AWS region
    required: true

runs:
  using: "composite"
  steps:
    # 保存したアーティファクトを取得します。
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: artifact
        path: ./archives
    # AWSクレデンシャルをセットアップします。
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.aws_account_key_id }}
        aws-secret-access-key: ${{ inputs.aws_secret_access_key }}
        aws-region: ${{ inputs.aws_default_region }}
    # リポジトリにログインし、イメージをプッシュします。
    - name: Helm login & push
      shell: bash
      run: |
        AWS_ECR_ACCOUNT_URL="${{ inputs.aws_account_id }}.dkr.ecr.${{ inputs.aws_default_region }}.amazonaws.com"
        aws ecr get-login-password --region ${{ inputs.aws_default_region }} | helm registry login --username AWS --password-stdin $AWS_ECR_ACCOUNT_URL
        helm push ./archives/microservices-manifests-${{ inputs.target }}-*.tgz oci://$AWS_ECR_ACCOUNT_URL/
