inputs:
  target:
    description: The target of resource
    required: true
  aws_account_id:
    description: AWS account id
    required: true
  aws_default_region:
    description: AWS region
    required: true

runs:
  using: "composite"
  steps:
    # 保存したアーティファクトを取得します．
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: artifact
    # リポジトリにログインします．
    - name: Helm registry login
      shell: bash
      run: |
        source ./github/script/export_envs.sh
        aws ecr get-login-password --region "${{ AWS_DEFAULT_REGION }}" | helm registry login --username AWS --password-stdin "${{ AWS_ECR_ACCOUNT_URL }}"
    # Helmのチャートをリポジトリにプッシュします．
    - name: Helm push
      shell: bash
      run: |
        source ./github/script/export_envs.sh
        helm push ./archives/microservices-manifests-${{ inputs.target }}-*.tgz oci://"${{ AWS_ECR_ACCOUNT_URL }}"/
