{{- define "dev.order.app.deployment" }}
      hostname: {{ .Values.global.serviceName }}-app
      containers:
        # Lumenコンテナ
        - name: lumen
          image: {{ .Values.global.serviceName }}-lumen:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: {{ .Values.global.serviceName }}-app-persistent-volume
              mountPath: /var/www/order
        - name: nginx
          image: {{ .Values.global.serviceName }}-nginx:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: {{ .Values.global.serviceName }}-app-persistent-volume
              mountPath: /var/www/order
      volumes:
        - name: {{ .Values.global.serviceName }}-app-persistent-volume
          persistentVolumeClaim:
            claimName: {{ .Values.global.serviceName }}-app-host-path-persistent-volume-claim
{{- end }}
