apiVersion: v1
kind: Namespace
metadata:
  name: microservices
  labels:
    env: {{ .Values.labels.env }}
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
  labels:
    env: {{ .Values.labels.env }}
