{{- define "prd.customer.app.deployment" }}
      hostname: {{ .Values.global.serviceName }}-app
      containers:
        # FastAPIコンテナ
        - name: fastapi
          image: {{ .Values.aws.accountId }}.dkr.ecr.{{ .Values.aws.region }}.amazonaws.com/{{ .Values.global.serviceName }}-fastapi-repository:{{ .Values.image.customer.fastapi }}
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
{{- end }}
