apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  namespace: istio-system
  name: customer-app-gateway
  labels:
      env: {{ .Values.general.env }}
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        name: http-customer-app
        protocol: HTTP
        number: 30000
      hosts:
        - "*"
