apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: services
  name: {{ .Values.global.serviceName }}-app-service
  labels:
    env: {{ .Values.global.env }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.global.serviceName }}
  template:
    metadata:
      labels:
        app: {{ .Values.global.serviceName }}
    spec:
      containers:
        - image: kennethreitz/httpbin
          imagePullPolicy: IfNotPresent
          name: {{ .Values.global.serviceName }}
          command:
            - gunicorn
            - -b
            - 0.0.0.0:8080
            - {{ .Values.global.serviceName }}:app
            - -k
            - gevent
          env:
            - name: WORKON_HOME
              value: /tmp
          ports:
            - containerPort: 8080
