apiVersion: v1
kind: Service
metadata:
  namespace: services
  name: {{ .Values.global.serviceName }}-service
  labels:
    env: {{ .Values.global.env }}
spec:
  selector:
    app: {{ .Values.global.serviceName }}
  ports:
    - name: http-httpbin
      port: 8080
      targetPort: 8080
