apiVersion: v1
kind: Service
metadata:
  namespace: services
  name: {{ .Values.global.serviceName }}-app-service
  labels:
    env: {{ .Values.global.env }}
spec:
  selector:
    app: {{ .Values.global.serviceName }}
  ports:
    - name: http-{{ .Values.global.serviceName }}
      port: {{ .Values.service.listenPort }}
      targetPort: 8080
