apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  namespace: services
  name: {{ .Values.global.serviceName }}-app-virtual-service
  labels:
    env: {{ .Values.global.env }}
spec:
  exportTo:
    - "."
  hosts:
    - "*"
  gateways:
    - {{ .Values.global.serviceName }}-app-gateway
  http:
    - route:
        - destination:
            host: {{ .Values.global.serviceName }}
            port:
              number: {{ .Values.service.listenPort }}
