apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: istio-gateway-application
  labels:
    env: {{ .Values.global.env }}
spec:
  project: infra
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    chart: gateway
    targetRevision: {{ .Values.application.dottedRevision }}
    helm:
      releaseName: istio-ingressgateway
      values: |
        {{- /* リクエストをIstio IngressGatewayに送信するためのService */}}
        service:
          type: NodePort
          ports:
            - name: http-customer
              {{- /* Nodeが待ち受けるポート番号 */}}
              nodePort: 30001
              {{- /* NodePort Serviceが待ち受けるポート番号 */}}
              port: 50001
              targetPort: 50001
            - name: http-orchestrator
              nodePort: 30002
              port: 50002
              targetPort: 50002
            - name: http-helloworld
              nodePort: 30003
              port: 50003
              targetPort: 50003
            - name: http-httpbin
              nodePort: 30004
              port: 50004
              targetPort: 50004
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: node.kubernetes.io/nodegroup
                      operator: In
                      values:
                        - ingress

  destination:
    server: https://kubernetes.default.svc
    namespace: istio-ingress
