apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: istio-base-application
  labels:
    env: {{ .Values.global.env }}
spec:
  project: infra
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    chart: base
    targetRevision: {{ .Values.application.dottedRevision }}
    helm:
      releaseName: istio-base
      values: |
        defaultRevision: "{{ .Values.application.hyphenatedRevision }}"
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
