apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: istio-gateway-application
  labels:
    env: {{ .Values.global.env }}
spec:
  project: infra
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    chart: gateway
    targetRevision: {{ .Values.application.dottedRevision }}
    helm:
      releaseName: istio-ingressgateway
      values: |
        {{- /* リクエストをIstio IngressGatewayに送信するためのService */}}
        service:
          type: NodePort
          ports:
            - name: http-helloworld
              port: 80
              targetPort: 80
              nodePort: 50000
            - name: http-httpbin
              port: 8080
              targetPort: 8080
              nodePort: 50001
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: node.kubernetes.io/nodegroup
                      operator: In
                      values:
                        - ingress

  destination:
    server: https://kubernetes.default.svc
    namespace: istio-ingress
