apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: services
  name: account-app-pod
  labels:
    app: account
    component: app
    env: {{ .Values.global.env }}
spec:
  replicas: 1
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0%
  selector:
    matchLabels:
      app: account
      component: app
      env: {{ .Values.global.env }}
  template:
    metadata:
      labels:
        app: account
        component: app
        env: {{ .Values.global.env }}
    spec:
{{- if eq .Values.global.env "dev" }}
  {{- include "dev.account.app.deployment" . }}
{{- end }}
{{- if eq .Values.global.env "prd" }}
  {{- include "prd.account.app.deployment" . }}
{{- end }}
