apiVersion: v1
kind: Service
metadata:
  namespace: services
  name: account-app-service
  labels:
    app: account
    component: app
    env: {{ .Values.global.env }}
spec:
  type: ClusterIP
  selector:
    app: account
    component: app
  ports:
    - name: http-{{ .Values.global.serviceName }}
      appProtocol: http
      port: {{ .Values.service.listenPort }}
      targetPort: 8080
