apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  namespace: services
  name: account-app-virtual-service
  labels:
    env: {{ .Values.global.env }}
spec:
  exportTo:
    - "."
  hosts:
    - "*"
  gateways:
    - mesh
  http:
    - name: account-route
      match:
        - uri:
            prefix: /account/
      route:
        - destination:
            host: account-app-service.services.svc.cluster.local
            port:
              number: 80
