apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  namespace: services
  name: account-app-virtual-service
  labels:
    env: {{ .Values.global.env }}
spec:
  exportTo:
    - "."
  hosts:
    - {{ .Values.global.serviceName }}-app-service
  gateways:
    - mesh
  http:
    - match:
        - port: {{ .Values.service.listenPort }}
      route:
        - destination:
            host: account-app-service
            port:
              number: {{ .Values.service.listenPort }}
