---
# Source: microservices-manifests-argocd/templates/application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: argocd-application
  labels:
      env: prd
spec:
  project: default
  source:
    repoURL: oci://.dkr.ecr..amazonaws.com/microservices-manifests-kubernetes
    targetRevision: 1.0.0
  destination:
    server: https://kubernetes.default.svc
    namespace: microservices
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
