apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: microservices
  name: customer-app-pod
  labels:
    app: customer
    component: app
spec:
  replicas: 1
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0%
  selector:
    matchLabels:
      app: customer
      component: app
  template:
    metadata:
      labels:
        app: customer
        component: app
    spec:
      hostname: customer-app-pod
      containers:
        # FastAPIコンテナ
        - name: fastapi
          image: ${SERVICE_NAME}-${VENDOR_NAME}:${CIRCLE_SHA1:0:7}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: customer-app-persistent-volume
              mountPath: /var/www/customer
      volumes:
        - name: customer-app-persistent-volume
          persistentVolumeClaim:
            claimName: customer-app-host-path-persistent-volume-claim
