{{- define "dev.account.app.persistent-volume" }}
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: services
  name: account-app-persistent-volume
  labels:
    app: account
    component: app
    env: {{ .Values.global.env }}
    type: hostPath
spec:
  storageClassName: standard
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /data/src/account
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - minikube
{{- end }}
