apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  namespace: services
  name: orchestrator-app-gateway
  labels:
    env: {{ .Values.global.env }}
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        name: http-{{ .Values.global.serviceName }}
        protocol: HTTP
        number: {{ .Values.ingressGateway.pod.listenPort }}
      hosts:
        - "*"
