apiVersion: v1
kind: Service
metadata:
  namespace: services
  name: {{ .Values.global.serviceName }}-service
  labels:
    app: orchestrator
    env: {{ .Values.global.env }}
spec:
  type: ClusterIP
  selector:
    app: orchestrator
  ports:
    - name: http-{{ .Values.global.serviceName }}
      appProtocol: http
      port: {{ .Values.service.listenPort }}
      targetPort: 8000
