apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  namespace: services
  name: orchestrator-app-virtual-service
  labels:
    env: {{ .Values.global.env }}
spec:
  exportTo:
    - "."
  hosts:
    - "*"
  gateways:
    - orchestrator-app-gateway
  http:
    - name: checkout-route
      match:
        - uri:
            prefix: /checkout/
      route:
        - destination:
            host: orchestrator-app-service
            port:
              number: {{ .Values.service.listenPort }}
