apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: argocd-application
spec:
  project: default
  source:
    repoURL: https://github.com/hiroki-it/microservices-manifests.git
    targetRevision: main
    path: kubernetes
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: microservices
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
