apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: microservices
  name: orchestrator-host-path-persistent-volume-claim
  labels:
    app: orchestrator
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      app: orchestrator
      type: hostPath
