apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Values.global.serviceName }}-app-gateway
  namespace: services
  labels:
    env: {{ .Values.global.env }}
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        name: http-{{ .Values.global.serviceName }}
        protocol: HTTP
        number: {{ .Values.ingressGateway.pod.listenPort }}
      hosts:
        - "*"
