apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.serviceName }}-service
  namespace: services
  labels:
    env: {{ .Values.global.env }}
spec:
  selector:
    app: {{ .Values.global.serviceName }}
  ports:
    - name: http-{{ .Values.global.serviceName }}
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.deployment.containerPort }}
