apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  namespace: services
  name: {{ .Values.global.serviceName }}-app-virtual-service
  labels:
    env: {{ .Values.global.env }}
spec:
  exportTo:
    - "."
  hosts:
    - "*"
  gateways:
    - {{ .Values.global.serviceName }}-app-gateway
  http:
    - match:
        - port: {{ .Values.ingressGateway.port }}
      route:
        - destination:
            host: {{ .Values.global.serviceName }}-app-service.app.svc.cluster.local
            port:
              number: {{ .Values.ingressGateway.port }}

