apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  namespace: istio-system
  name: orchestrator-app-virtual-service
  labels:
      env: {{ .Values.general.env }}
spec:
  exportTo:
    - "*"
  hosts:
    - "*"
  gateways:
    - orchestrator-app-gateway
  http:
    - name: checkout-route
      match:
        - uri:
            prefix: /checkout/
      route:
        - destination:
            host: orchestrator-service.microservices.svc.cluster.local
            port:
              number: 80
