apiVersion: v1
kind: Service
metadata:
  namespace: microservices
  name: orchestrator-service
  labels:
    app: orchestrator
    env: {{ .Values.general.env }}
spec:
  type: ClusterIP
  selector:
    app: orchestrator
  ports:
    - name: http-orchestrator
      appProtocol: http
      port: 80
      targetPort: 8000
