name: helm-template

on:
  push:
    branches:
      - release/**

jobs:
  helm-template:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Git config
        run: |
          git config --local user.email "hasegawafeedshop@gmail.com"
          git config --local user.name "github-actions"
          git config pull.rebase false
      - name: Setup Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.8.1
      - name: Helm lint
        run: |
          helm lint ./kubernetes ./istio ./argocd ./eks ./operator/istio -f ./values/prd.yaml
      - name: Helm package
        run: |
          helm package ./kubernetes ./istio ./argocd ./eks ./operator/istio
      - name: Helm template
        run: |
          helm template release microservices-manifests-kubernetes-*.tgz -f values/prd.yaml >| ./release/prd/kubernetes.yaml
          helm template release microservices-manifests-istio-*.tgz -f values/prd.yaml >| ./release/prd/istio.yaml
          helm template release microservices-manifests-argocd-*.tgz -f values/prd.yaml >| ./release/prd/argocd.yaml
          helm template release microservices-manifests-eks-*.tgz -f values/prd.yaml >| ./release/prd/eks.yaml
          helm template release microservices-manifests-operator-istio-*.tgz -f values/dev.yaml >| ./release/prd/istio-operator.yaml
      - name: Git commit & push
        run: |
          git add ./release
          if [ -z "$(git status --porcelain)" ]; then
            echo "マニフェストファイルに変更点がないため，GitHub Actionは終了しました．"
            exit 0
          fi
          git commit -m "helm templateを実行し，マニフェストファイルを自動生成しました．"
          git pull
          git push origin HEAD
