name: plan-manifests

on:
  push:
    branches:
      - main
      - release/**

jobs:
  plan-manifests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # gitコマンドをセットアップします。
      - name: Git config
        run: |
          git config --local user.email "hasegawafeedshop@gmail.com"
          git config --local user.name "github-actions"
          git config pull.rebase false
      # helmコマンドをセットアップします。
      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.1
      # チャートの静的解析を実行します。
      - name: Helm lint
        run: |
          source ./.github/ops/helm_lint.sh
      # マニフェストファイルを生成します。
      - name: Helm template
        run: |
          source ./.github/ops/helm_template.sh
      # 生成されたマニフェストファイルをプッシュします。
      - name: Git commit & push
        run: |
          git checkout -b release/manifest
          git add ./release
          if [ -z "$(git status --porcelain)" ]; then
            echo "マニフェストファイルに変更点がないため、GitHub Actionは終了しました。"
            exit 0
          fi
          git commit -m "helm templateを実行し、マニフェストファイルを自動生成した"
          git push -f origin HEAD
